AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'examples/**/*'
    - 'k6/**/*'
    - 'gemfiles/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Gemspec/DevelopmentDependencies:
  EnforcedStyle: 'gemspec'
