name: Benchmark
on:
  pull_request:
    branches:
      - master

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: 14
          cache: 'yarn'
          cache-dependency-path: 'k6/yarn.lock'

      - name: Use Ruby
        uses: ruby/setup-ruby@2a9a743e19810b9f3c38060637daf594dbd7b37f
        with:
          working-directory: ./k6/graphql-api
          ruby-version: '3.3'
          bundler-cache: true

      - name: Start GraphQL API with hive enabled
        working-directory: ./k6/graphql-api
        run: |
          bundle
          bundle exec puma -t 0:1 -p 9292 & sleep 5
        env:
          HIVE_ENABLED: 'true'

      - name: Start GraphQL API with hive disabled
        working-directory: ./k6/graphql-api
        run: |
          bundle
          bundle exec puma -t 0:1 -p 9291 & sleep 5
        env:
          HIVE_ENABLED: 'false'

      - name: Start Fake Usage API
        working-directory: ./k6/
        run: |
          yarn
          node usage-api.js & sleep 5s

      - name: Run k6 local test
        uses: grafana/k6-action@655099b3d4b0a2b748f84e9e0811616617f8bbc5
        env:
          GITHUB_PR: ${{ github.event.number }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_TOKEN: ${{ secrets.GH_PA_TOKEN }}
        with:
          filename: k6/k6.js
