name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@2a9a743e19810b9f3c38060637daf594dbd7b37f
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - run: bundle exec rake rubocop
      
  test:
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '3.1'
          - '3.2'
          - '3.3'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@2a9a743e19810b9f3c38060637daf594dbd7b37f
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - run: bundle exec rake spec
